Added map marker clustering
Mdominykas/EncounterMe-name-subject-to-change pull request #45
Opened 2021-09-30 13:45 UTC by Waltzerizm

- Now the markers cluster when there is multiple markers in one place
- Added some data to the location database for marker clustering demonstration
- Installed Xamarin.Forms.GoogleMaps.Clustering NuGet package

2021-10-01 10:26 UTC, Mdominykas commented on Encountify/Views/MapPage.xaml
> +                                 VerticalOptions="FillAndExpand"
Seems that there are 17 extra spaces

2021-10-01 10:26 UTC, Mdominykas requested changes
It works well, however I noticed that when you only have 2 locations and LoadDummyData will try to add more, it will raise and exception and not load anything, since location1 already exists in the database.
For that I believe MockDataStore needs to be nearly completely rewrote (I have already investigated it, so it would be quite easier for me, thus I will try to change it tommorow).
for now to avoid exceptions I suggest addiding location1, location2, ..., location8 to list and inserting to database only those that exceed db.Table<Location>.Count()

2021-10-02 11:18 UTC, Waltzerizm commented on Encountify/Views/MapPage.xaml
> +                                 VerticalOptions="FillAndExpand"
Didn't noticed, thank you! Fixed

2021-10-02 11:19 UTC, Waltzerizm commented
Reverted the changed on the LoadDummyData() method since Dominykas work on it. Clustering option is still there, so if you want to see it make sure you have enough markers in one spot added!

2021-10-03 18:35 UTC, Mdominykas commented on Encountify/Services/MockDataStore.cs
> +
If you remove this new line I will likely not have to solve merge conflict :)

2021-10-03 18:36 UTC, Mdominykas approved these changes
It works well for me

2021-10-04 11:17 UTC, MigleMic approved these changes
Just checked it out, works great :)

2021-10-04 11:27 UTC, merged